env:
  global:
    - DATE=$(date +%Y-%m-%d)
    - PACKAGE_VERSION=$DATE-$TRAVIS_BUILD_NUMBER
    - PACKAGE_NAME=tns-core-modules
    - NODE_VERSION=5.10.1
    - EMULATOR_API_VER=21
    - RUNTIMEVERSION=next
    - AVD_NAME=Arm$EMULATOR_API_VER
addons:
  artifacts:
    paths:
      - "$HOME/test-run-results$PACKAGE_VERSION.xml"
sudo: false
dist: trusty
language: android
node_js:
  - 4.2.3
jdk:
  - oracle-java8-installer
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-$EMULATOR_API_VER
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-$EMULATOR_API_VER
before_script:
  - nvm install $NODE_VERSION
  - npm install -g grunt-cli
  - npm install
  - echo no | android create avd --force -n $AVD_NAME -t android-$EMULATOR_API_VER --abi default/armeabi-v7a -c 12M
  - emulator -avd $AVD_NAME -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - java -version
  - grunt default --verbose &&
    FULL_PACKAGE_VERSION=`node -e 'console.log(require("./bin/dist/tns-core-modules/package.json").version);'` &&
    (cd tns-platform-declarations && npm pack) &&
    wget -O ./nativescript.tgz "https://s3.amazonaws.com/nativescript-ci/build_result/nativescript.tgz" && 
    echo no | npm install -g nativescript.tgz --ignore-scripts > /dev/null && tns usage-reporting disable && tns error-reporting disable &&
    grunt buildOnlyTestsApp --verbose --platform=Android --modulesPath=./bin/dist/$PACKAGE_NAME-$FULL_PACKAGE_VERSION.tgz --runtimeVersion=$RUNTIMEVERSION --emuPId=.*emulator.* --avd=$AVD_NAME --showEmu=false > /dev/null &&
    grunt runOnlyTestsApp --verbose --platform=Android --modulesPath=./bin/dist/$PACKAGE_NAME-$FULL_PACKAGE_VERSION.tgz --emuPId=.*emulator.* --avd=$AVD_NAME --showEmu=false
  - node ./build/travis-scripts/check-testrun-broken.js
  - adb pull /data/data/org.nativescript.TestsApp/files/test-results.xml &&
    mv test-results.xml ~/test-run-results$PACKAGE_VERSION.xml
before_deploy:
  - mv bin/dist/$PACKAGE_NAME-$FULL_PACKAGE_VERSION.tgz ../.deploymentpackage
  - mv build ../
  - cd ..
  - rm -rf NativeScript
  - tar -zxvf .deploymentpackage
  - mv package $PACKAGE_NAME
  - cd $PACKAGE_NAME
  - rm ../.deploymentpackage
  - mv ../build ./
  - node ./build/travis-scripts/add-publishConfig.js next
deploy:
  provider: npm
  email: nativescript@telerik.com
  on:
    branch: master
    skip_cleanup: true
  api_key:
    secure: j2gE5jnGSuCFy7s3pDB6Or2j+vhlRYIlSSB1mDI7R5PvpV0kWr8yE1rLnyqeb0pI7WY/36SV/0NZCClJhlrZFvd7QvaP3+55cGX3ijmsDp8WxfQRyHppA9RZuMFujG7swFr/s0RmoYgO9mYNe46lJTX8m0HZeNN2qlAC7LDD3x8=
