name: 'apps/automated/ios'
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
      - 'ci/**'
  pull_request:
  workflow_dispatch:

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-ios:
    # runs-on: macos-latest
    runs-on: warp-macos-15-arm64-6x

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      # - name: ActionDebugger By Warpbuild
      #   uses: Warpbuilds/action-debugger@v1.3

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 23.5.0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@826660b82addbef3abff5fa871492ebad618c9e1 # v4.3.3
        with:
          main-branch-name: 'main'

      - name: Install NativeScript
        run: |
          npm i -g nativescript --ignore-scripts
          ns usage-reporting disable
          ns error-reporting disable
          # ns doctor

      - name: Setup
        run: npm run setup

      - name: Unit Tests
        run: npx nx run-many --target=test --configuration=ci --projects=core

      - name: Start iOS Simulator
        uses: futureware-tech/simulator-action@dab10d813144ef59b48d401cd95da151222ef8cd # v4
        with:
          model: 'iPhone 16 Pro'
          os_version: '18.4'

      - name: Run tests on iOS Simulator
        run: npx nx test apps-automated -c=ios
