name: 'apps/automated/ios'

on:
  push:
    branches:
      - main
      - 'ci/**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-ios:
    # runs-on: macos-latest
    runs-on: [self-hosted, macOS, ARM64]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 23.5.0

      - name: Install NativeScript
        run: |
          npm i -g nativescript --ignore-scripts --legacy-peer-deps
          ns usage-reporting disable
          ns error-reporting disable
          # ns doctor

      - name: Setup
        run: npm run setup

      - name: Unit Tests
        run: npx nx run-many --target=test --configuration=ci --projects=core

      - name: Start iOS Simulator
        uses: futureware-tech/simulator-action@v4
        with:
          model: 'iPhone 15'
          os_version: '17.5'

      - name: Run tests on iOS Simulator
        run: node tools/scripts/run-automated.js ios
