# TODO: modify to build android & ios types first and then merge into types
name: '@nativescript/types -> npm'

on:
  push:
    branches: [ 'main' ]
    paths:
      - 'packages/types/**'

env:
  NPM_TAG: 'next'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Todo
        run: |
          echo "TODO: implement action"
#      - uses: actions/checkout@v2
#
#      - name: Setup
#        run: npm install
#
#      - name: Generate Version
#        working-directory: packages/types
#        run: |
#          echo NPM_VERSION=$(node -e "console.log(require('./package.json').version);")-$NPM_TAG-$(date +"%m-%d-%Y")-$GITHUB_RUN_ID >> $GITHUB_ENV
#
#      - name: Bump Version
#        working-directory: packages/types
#        run: npm version $NPM_VERSION
#
#      - name: Build @nativescript/types
#        run: npx nx run core:build
#
#      - name: Publish @nativescript/types
#        working-directory: dist/packages
#        env:
#          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
#        run: |
#          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ../../.npmrc
#          echo "Publishing @nativescript/types@$NPM_VERSION to NPM with tag $NPM_TAG..."
#          npm publish nativescript-types-$NPM_VERSION.tgz --tag $NPM_TAG
